### ISSUE TITLE
failed to find a ClientStateResponseWriter or UnderlyingResponseWriter in: *http.response

### ISSUE THREAD

**Issue by natefinch** [volatiletech/authboss#180]
I presume this means I'm missing some plugin or something, but the error doesn't give me any clue as to what I have to do to fix this, even going into the code.  

Little help, please?

```
2018/08/16 08:36:52 http: panic serving [::1]:51660: failed to find a ClientStateResponseWriter or UnderlyingResponseWriter in: *http.response
goroutine 32 [running]:
net/http.(*conn).serve.func1(0xc4200f1b80)
	/usr/local/go/src/net/http/server.go:1726 +0x11b
panic(0x1695e20, 0xc4201b21a0)
	/usr/local/go/src/runtime/panic.go:502 +0x24a
github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss.MustClientStateResponseWriter(0x17bbe80, 0xc4202382a0, 0x0)
	/Users/finchnat/src/github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/client_state.go:162 +0x295
github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss.setState(0x17bbe80, 0xc4202382a0, 0x175d3af, 0x7, 0x0, 0x1759b2d, 0x3, 0xc4202128a0, 0x16)
	/Users/finchnat/src/github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/client_state.go:277 +0x4d
github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss.putState(0x17bbe80, 0xc4202382a0, 0x175d3af, 0x7, 0x1759b2d, 0x3, 0xc4202128a0, 0x16)
	/Users/finchnat/src/github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/client_state.go:269 +0x83
github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss.PutSession(0x17bbe80, 0xc4202382a0, 0x1759b2d, 0x3, 0xc4202128a0, 0x16)
	/Users/finchnat/src/github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/client_state.go:240 +0x72
github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/auth.(*Auth).LoginPost(0xc4200e8728, 0x17bbe80, 0xc4202382a0, 0xc4202ca100, 0x0, 0x0)
	/Users/finchnat/src/github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/auth/auth.go:100 +0x104e
github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/auth.(*Auth).LoginPost-fm(0x17bbe80, 0xc4202382a0, 0xc4201abd00, 0x0, 0x0)
	/Users/finchnat/src/github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/auth/auth.go:36 +0x55
github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/defaults.errorHandler.ServeHTTP(0xc420228530, 0x17ba7c0, 0xc420228150, 0x17bbe80, 0xc4202382a0, 0xc4201abd00)
	/Users/finchnat/src/github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/defaults/error_handler.go:39 +0x62
net/http.(*ServeMux).ServeHTTP(0xc4202247b0, 0x17bbe80, 0xc4202382a0, 0xc4201abd00)
	/usr/local/go/src/net/http/server.go:2337 +0x1a3
github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/defaults.(*Router).ServeHTTP(0xc42022d660, 0x17bbe80, 0xc4202382a0, 0xc4201abd00)
	/Users/finchnat/src/github.com/Mattel/archimedes/vendor/github.com/volatiletech/authboss/defaults/router.go:69 +0x214
net/http.StripPrefix.func1(0x17bbe80, 0xc4202382a0, 0xc4201abc00)
	/usr/local/go/src/net/http/server.go:1986 +0x20d
net/http.HandlerFunc.ServeHTTP(0xc4201acde0, 0x17bbe80, 0xc4202382a0, 0xc4201abc00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201acdb0, 0x17bbe80, 0xc4202382a0, 0xc4201abc00)
	/usr/local/go/src/net/http/server.go:2337 +0x1a3
github.com/Mattel/archimedes/api.logHandler.ServeHTTP(0xc4200eab90, 0x17b7260, 0xc4201acdb0, 0x17bbe80, 0xc4202382a0, 0xc4201abc00)
	/Users/finchnat/src/github.com/Mattel/archimedes/api/server.go:104 +0x181
net/http.serverHandler.ServeHTTP(0xc4202640d0, 0x17bbe80, 0xc4202382a0, 0xc4201abc00)
	/usr/local/go/src/net/http/server.go:2694 +0x1e4
net/http.(*conn).serve(0xc4200f1b80, 0x17bc2c0, 0xc4202054c0)
	/usr/local/go/src/net/http/server.go:1830 +0x11f2
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x6e4
```

**Comment by natefinch** [comment]
Ahh, nevermind I figured it out (of course, just after I posted this).  I need to wrap my endpoints with Authboss.LoadClientStateMiddleware

**Comment by aarondl** [comment]
I don't disagree with that. Though in my defense this is documented as the only truly required middleware: https://github.com/volatiletech/authboss/tree/v2#middlewares :)

I've changed the error message to be:
```go
		panic(fmt.Sprintf("ResponseWriter must be a ClientStateResponseWriter or UnderlyingResponseWriter in (see: authboss.LoadClientStateMiddleware): %T", w))
```

Hopefully this is more acceptable.

**Comment by natefinch** [comment]
Great!   Just trying to help the next person that misses this.  Yes, it's well-documented, but there's an awful lot to ingest when getting up to speed on Authboss.  Thanks for the project, btw :)
